name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  Run-Tests:

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout pytket-mbqc
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install pytket-mbqc
        run: pip install .

      - name: Type Check
        run: mypy ocvqc_py/ --warn-unused-ignores

      - name: Lint Check
        run: ruff check

      - name: Format Check
        run: ruff format --check

      - name: Run Tests
        run: pytest --cov-fail-under=100 --cov-report term-missing:skip-covered --cov=ocvqc_py/ tests/ --durations=10

      - name: Examples check
        run: pytest --nbmake example_notebooks/*.ipynb


  Build-Documentation:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout pytket-mbqc
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pytket-benchmarking
        run: pip install .

      - name: Check Documentation coverage
        run: docstr-coverage ocvqc_py

      - name: Build documentation
        run: |
          make html

      - name: Save documentation
        uses: actions/upload-artifact@v5
        with:
          name: docs_html
          path: build/html
